development:
  adapter: postgis
  database: gh_instant_development
  pool: 5
  username: housing_su
  password: housing
  timeout: 5000
  schema_search_path: "public,postgis"
  script_dir: "/usr/pgsql-9.3/share/contrib/postgis-2.1/"

test:
  adapter: postgis
  encoding: unicode
  database: location_apis_test
  pool: 5
  username: housing_su
  password: housing